### ISSUE TITLE
Bugs in the Python interface tests

### ISSUE THREAD

**Issue by Daeinar** [stp/stp#144]
Hi!

Today I had some time to check the tests for the Python interface, which currently don't pass, see the commit https://github.com/stp/stp/commit/dc17c5af965b3addf9337278c9744a11b7c4c0cd by @delcypher.

It seems there are two bugs, both caused in `test_pushpop()`, see https://github.com/stp/stp/blob/master/tests/api/python/tests.py.in#L129

(1) The first bug is caused by an empty call to `s.check()` in the following line:

https://github.com/stp/stp/blob/master/tests/api/python/tests.py.in#L137 

As a consequence the assert over here fails:

https://github.com/stp/stp/blob/master/lib/Simplifier/consteval.cpp#L56. 

Changing it to `assert(number_of_children >= 0);` would resolve the issue, however I suppose the comparison `>= 1` has a purpose and I am not sure what the consequences are if it is set to `>= 0`.

(2) The second bug is caused by this line

https://github.com/stp/stp/blob/master/tests/api/python/tests.py.in#L154

and makes the following assert fail:

https://github.com/stp/stp/blob/master/include/stp/Simplifier/SubstitutionMap.h#L158

It seems checking twice for the value of a variable (namely `s.check(b==1)` and `s.check(b==2)`) causes  this bug, since `b` is already in the `SolverMap` after the first check. Commenting the above assert line out makes the test pass. But again: randomly changing/removing asserts for no obvious reason is probably not the best idea.

Maybe someone more familiar with the project (@msoos? @delcypher?) knows what's going on over there?

Cheers,
Philipp

**Comment by msoos** [comment]
OK fixed in commit 987da829532fb68001c83d0ea5b8a9fb10c9e06e. It was really simple actually. We needed to push() before solving and then pop(), otherwise the current state would get mixed up with the assumed setting. For example, for the current check we wanted to assume a==b. The next time, we wanted to assume a>b. But of course a==b should not have remained in the state. However, it did. To get rid of it, we first push() the state to save it, then we call the solve with the assumption, then we go back to the old state by pop()-ing it.

**Comment by msoos** [comment]
Thanks @Daeinar  for the report! Was loooong time coming, but we made it :) Thanks again!

**Comment by Daeinar** [comment]
@msoos: Thanks for fixing this and explaining how you solved it, makes sense. :)
