### ISSUE TITLE
Support (set-option :produce-models true)

### ISSUE THREAD

**Issue by msoos** [stp/stp#151]
The model can of course be printed and is known by STP. It can be queried in the python interface and it can be asked to be printed on the console. For example:

```
$ ./stp --print-counterex tmp.smt2 
ASSERT( B0 = 0x00000000 );
ASSERT( B1 = 0x00000000 );
ASSERT( C1 = 0x00000000 );
sat
```

for a file:

```
$ cat tmp.smt2 
; (set-option :produce-models true)
(set-logic QF_BV)
(declare-fun B0 () (_ BitVec 32))
(declare-fun B1 () (_ BitVec 32))
(declare-fun C1 () (_ BitVec 32))
(assert (= C1 (bvadd B0 B1)))
(assert (= C1 (bvsub B0 B1)))
(check-sat)
; (get-value C1)
```

If I add the set-option in then STP complains. So, we have have a (small) deficiency with the SMT-LIBv2 parser. Let me try to add the support over the weekend.

**Comment by rsas** [comment]
Any updates on the model retrieval support? We'll be heavily using models in our current program synthesis efforts, an alternative to z3 would be great.

**Comment by delcypher** [comment]
@rsas I'm afraid I don't have the time or expertise to work on this but out of curiosity are you using ``(get-value)`` or ``(get-model)`` if you have lots of variables ``(get-model)`` might be faster if you need the values of all variables.

**Comment by rsas** [comment]
Thanks for the info. We are using ``(get-value)`` as printed by KLEE's ``ExprSMTLIBPrinter``.

**Comment by rsas** [comment]
@msoos @delcypher: could you please give me some pointers to the code to look at for this feature? We are finally able to synthesize programs in Souper and running it with a different solver than z3 would be great.

**Comment by delcypher** [comment]
@rsas That's great news about souper. I really don't have expertise here as I joined the STP project to fix the build system and testing. I don't really know how much of the internals of the code work but I can think of two possible starting points

- see how the ``--print-counterex`` flag is implemented.
- See how the following functions in [include/stp/c_interface.h] (https://github.com/stp/stp/blob/master/include/stp/c_interface.h) are implemented
```
//! Return the counterexample after a failed query.
Expr vc_getCounterExample(VC vc, Expr e);

//! Return an array from a counterexample after a failed query.
void vc_getCounterExampleArray(VC vc, Expr e, Expr** indices, Expr** values,
                               int* size);

//! get size of counterexample, i.e. the number of variables/array
// locations in the counterexample.
int vc_counterexample_size(VC vc);
```

IIRC the SMT-LIBv2 parser communicates with STP via [include/stp/cpp_interface.h](https://github.com/stp/stp/blob/master/include/stp/cpp_interface.h) so you would probably want to add a method there to get the model. So when the parser sees ``(get-model)`` or ``(get-value)`` it can use the ``cpp_interface`` to do that.

Hope that helps. If I had time I would definitely work on this feature because it's clearly very useful.

**Comment by erakadjiev** [comment]
Hello,

Any news about this feature? I also rely on the `(get-value)` command and am interested if there are plans to implement the support in STP soon?
Fortunately, it's not critical for me, because currently I'm using @delcypher 's very useful stpwrap2. However, having this in STP would be cleaner.
Thank you!

**Comment by msoos** [comment]
We have been working quite a lot in the past days. This is up next. By the way, the python binding is super-useful, have you tried it yet? It works flawlessly now.

**Comment by rsas** [comment]
That's great news. I haven't tried the python binding yet, but I will certainly give it a try!

**Comment by erakadjiev** [comment]
Thank you, Mate! Looking forward to it!
I haven't used the Python binding yet, either.

**Comment by msoos** [comment]
Well, I didn't get here, again. I'm not the master of flex. I'm just slowly trying to make myself familiar with the codebase, cleaning up while I go along. It'll take time, but I'm getting there. Just take a look at my commits the past few weeks.

**Comment by rsas** [comment]
@msoos thanks for your effort! Don't worry, for now I have a simple wrapper inspired by @delcypher that I use to retrieve the model values. It works fine for me.

**Comment by delcypher** [comment]
Perhaps we should move this to the 1.2 release so we can release sooner?

**Comment by TrevorHansen** [comment]
d9224937d4f4521250a3ce8f5535cd918fc85940 introduces partial support for get-value (just for bitvector and boolean variables) so:

(set-logic QF_BV)
(declare-fun B0 () (_ BitVec 32))
(declare-fun B1 () (_ BitVec 32))
(declare-fun C1 () (_ BitVec 32))
(declare-fun D () Bool )
(assert (= C1 (bvadd B0 B1)))
(assert (= C1 (bvsub B0 B1)))
(check-sat)
(get-value (C1 D))

will produce:

sat
(
( |C1| (_ bv0 32) )
( |D| false )
)

Handling get-model including arrays, and get-value for arbitrary expressions is more difficult.  If anyone wants it, we need to discuss how it should work.

**Comment by msoos** [comment]
Wow, great work!

**Comment by TrevorHansen** [comment]
`````
(set-option :produce-models true)
(set-logic QF_BV)
(declare-fun B0 () (_ BitVec 32))
(declare-fun B1 () (_ BitVec 32))
(declare-fun C1 () (_ BitVec 32))
(assert (= C1 (bvadd B0 B1)))
(assert (= C1 (bvsub B0 B1)))
(check-sat)
(get-value ( C1 ) )
```
Since d9224937d4f4521250a3ce8f5535cd918fc85940 the above works like you'd expect. So I'll close this case until someone needs a more advanced "get-value" impementation.
