### ISSUE TITLE
Error Building STP Example

### ISSUE THREAD

**Issue by aruneshpa** [stp/stp#167]
I built the STP source. The build went through. Then I tried to build the examples/simple directory. I followed the instructions and created a bin directory. There I ran cmake which passed. But when I am building it using "make" it is giving me some error with GLIBCXX. 
Output of cmake -  
CC=/router/bin/gcc.c4.7.0-p1 CXX=/router/bin/g++.c4.7.0-p1 cmake ../
-- The C compiler identification is GNU 4.7.0
-- The CXX compiler identification is GNU 4.7.0
-- Check for working C compiler: /router/bin/gcc.c4.7.0-p1
-- Check for working C compiler: /router/bin/gcc.c4.7.0-p1 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /router/bin/g++.c4.7.0-p1
-- Check for working CXX compiler: /router/bin/g++.c4.7.0-p1 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
Using STP rooted at /usr/local/src/stp-master/build
STP include paths are: /usr/local/src/stp-master/build/include
STP Static Library target is: libstp_static
STP Shared Library target is: libstp
STP executable: stp
Using STP shared library
Full path to STP binary is STP_FULL_PATH-NOTFOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/stp-master/examples/simple/bin

Output of make-
/usr/local/src/stp-master/build/lib/libstp.so: undefined reference to `std::__detail::_List_node_base::_M_unhook()@GLIBCXX_3.4.15'

/usr/local/src/stp-master/build/lib/libstp.so: undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)@GLIBCXX_3.4.15'

/usr/local/src/stp-master/build/lib/libstp.so: undefined reference to `std::__detail::__prime_list@GLIBCXX_3.4.10'

/usr/local/src/stp-master/build/lib/libstp.so: undefined reference to `std::_Hash_bytes(void const*, unsigned long, unsigned long)@CXXABI_1.3.5'

/usr/local/src/stp-master/build/lib/libstp.so: undefined reference to `std::ctype<char>::_M_widen_init() const@GLIBCXX_3.4.11'

Is this a library version issue or it is there because of gcc version. I tried the compilation with gcc-4.5 and gcc-4.7 .
I have libstdc++.so.6 in my /usr/lib

**Comment by delcypher** [comment]
It is likely that you've mixed up the compiler used to build STP and the the compiler you're using to build the example leading to linking errors with ``libstdc++``. Either that or you compiler isn't correctly configured. This isn't something I can debug for you.

An alternative you could try is to link the example against the static ``libstp.a`` library instead. The example has an option you can use to control this

```
cmake -DUSE_STP_SHARED_LIBRARY:BOOL=OFF /path/to/example/source
```

**Comment by aruneshpa** [comment]
Thanks @delcypher 
Using this flag I was successful to build the example. But again when I am trying to run it , it gives me this error-
[root@vinayts-lab-lnx bin]# ./stp-example
./stp-example: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.10' not found (required by ./stp-example)
./stp-example: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ./stp-example)
./stp-example: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by ./stp-example)

I am sure that I used same version of gcc compilers for both STP and examples. Not sure what to do. Do i need to update my glibc and libstdc++?

**Comment by delcypher** [comment]
Okay I think I know what's wrong. Your compiler ``/router/bin/g++.c4.7.0-p1`` is using a different ``libstdc++`` to the one available at `` /usr/lib64/libstdc++.so.6``. You will probably find that if you try to build **any C++ application using your compiler** that it won't run because the dynamic loader will try to load a different version of ``libstdc++`` to one being used by your compiler.

You could try to hack around this by letting the linker know where the correct version of ``libstdc++`` lives by

* using the ``LIBRARY_PATH`` environment variable (read ``man gcc``) when building the STP example against the shared library (``libstp.so``)
OR
* Using the ``LD_LIBRARY_PATH`` environment variable (read ``man ld.so``) with trying to run the STP example when it was linked against the static STP library (``libstp.a``).

Fundamentally though, your system is not configured correctly which **you need to fix**.

Also as aside... why are you compiling as root! That is never necessary and is a recipe for disaster!

**Comment by msoos** [comment]
Dear @aruneshpa,

@delcypher  is very right. Given how badly your system is broken you may want to start over -- installing a new distribution. We simply **CANNOT** help you, you need to first help yourself by using a non-broken system. Later, any specifically STP-related problems we'll be able to help you with.

Cheers,

Mate
