### ISSUE TITLE
Decide on STP release version numbering

### ISSUE THREAD

**Issue by delcypher** [stp/stp#181]
I put ``1.1.0`` simply because the STP PPA package is ``1.0+1SNAPSHOT20141101-0~trusty`` current (i.e. a snapshot after 1.0).

I'd like to follow [semantic versioning](http://semver.org/) so I'm wondering if we should actually start with ``1.0.0`` instead.

@msoos Thoughts?

**Comment by msoos** [comment]
I agree with semantic versioning. There was an STP2 by Vijay at one point (see Sourceforge), so I put 3.0.0 at the top of the CMakeLists.txt.

The SONAME is simply ends with "3", this seems to be the way it's done in most Linux libraries:

```
$ objdump -p libstp.so.3.0.0 | grep SONAME
  SONAME               libstp.so.3
```

and the installed files are with full version:

```
$ ll *stp*
-rw-r--r-- 1 root root 109311302 Apr 19 15:52 libstp.a
lrwxrwxrwx 1 root root        11 Apr 22 23:51 libstp.so -> libstp.so.3
lrwxrwxrwx 1 root root        15 Apr 22 23:51 libstp.so.3 -> libstp.so.3.0.0
-rw-r--r-- 1 root root  36611101 Apr 22 23:51 libstp.so.3.0.0
```

What we also need to decide is where we're going to update the version. I hate to always manually update the CMakeLists. I used the CPACK_PACKAGE_VERSION_MAJOR / MINOR / PATCH because in case we decide to use CPack for tarball creation, it's re-usable. We could also get these values automatically from the GIT: the nearest tagged version could be used. I do this for CryptoMiniSat. However, when releasing it, we would need to manually enter these numbers otherwise, since there would be no GIT, the version detection would fail. Or we could ask CPack to generate a version number automagically on tarball generation... that would be a really nice trick, actually. Should I try doing that?

What do you think of the above?

**Comment by delcypher** [comment]
I'm not convinced with the choice of ``3.0.0``. We haven't really changed the public API since STP 2 so it probably ought to be ``2.1.0`` but a lot has changed internally so I'm happy to bump to 3 if you want.

I think we'll need to play with tarball generation to see what the best approach is.

**Comment by msoos** [comment]
You are right of course. We should leave it at 2.x. Yes, a lot has changed, but the interface has not, so probably 2.1 is good. Thanks for the tarball generation issue opening. And fixing the build. And all the other help :)

**Comment by delcypher** [comment]
Okay 2.1 it is :)
