### ISSUE TITLE
Compile STP with emscripten and put it online on GitHub page

### ISSUE THREAD

**Issue by msoos** [stp/stp#191]
For people to play with it! :)

**Comment by rgov** [comment]
[Ace](http://ace.c9.io/) is an open source embeddable code editor. It already has a Scheme syntax highlighter, which we could extend with SMT-LIB2 keywords. But the C API doesn't easily let you parse SMT-LIB2.

**Comment by rgov** [comment]
To start with, here's how to get CryptoMiniSat building with Emscripten:

```
git clone https://github.com/msoos/cryptominisat.git
cd cryptominisat
mkdir build && cd build
emcmake cmake ..
make
```

And then

```
$ time node cryptominisat_simple.js --verb=0 <<EOF
> p cnf 2 3
> 1 0
> -2 0
> -1 2 3 0
> EOF
Calling stub instead of signal()
Calling stub instead of signal()
Reading from standard input... Use '-h' or '--help' for help.
s SATISFIABLE
v 1 -2 3 0
 

real	0m1.102s
user	0m0.463s
sys	0m0.097s
```

Cool, now we need MiniSat. That required some patching to get it to build. (Unfortunately my patch mixes actual bug fixes with Makefile hacks.)

```
git clone https://github.com/niklasso/minisat.git
cd minisat
git apply <(curl https://gist.githubusercontent.com/rgov/62f568a0b886824c32c3/raw)
mkdir prefix
emmake make config prefix=$(pwd)/prefix
emmake make install-headers install-lib
```

Then I hacked on STP a little, first because I couldn't get it to automatically find MiniSat, then because there were a few compiler errors in `abc`. Finally it died at the linking stage bcause of some issue with `-fPIC`, which I haven't resolved, so I went ahead and disabled the shared library.

```
git clone https://github.com/stp/stp
cd stp
git apply <(curl https://gist.githubusercontent.com/rgov/b7bbd2eb67e8f51ccabe/raw)
mkdir build && cd build
emcmake cmake .. -DMINISAT_INCLUDE_DIR=/tmp/minisat/prefix/include -DMINISAT_LIBRARIES=/tmp/minisat/prefix/lib/libminisat.so -Dcryptominisat4_DIR=/tmp/cryptominisat/build/ -DBUILD_SHARED_LIBS=NO -DENABLE_PYTHON_INTERFACE=OFF

# Oops, try building twice in case it fails on the first pass because some
# generated header isn't there yet
make || make
```

Strangely it claims to fail during linking:

```
[ 97%] Linking CXX executable ../../stp_simple.js
WARNING  root: emcc: cannot find library "cryptominisat4"
WARNING  root: emcc: cannot find library "m4ri"
```

But it seems to work!

```
$ time node stp_simple.js < ../tests/query-files/sample-cvc-tests/bvashr-valid.cvc 
Valid.
 

real	0m1.218s
user	0m0.666s
sys	0m0.128s
```

**Comment by rgov** [comment]
It weighs about 8MB compiled, and seems to be self-contained. I haven't done any real performance tests, but just that test case I used above takes 200-300x longer.

**Comment by msoos** [comment]
Wow. That's some amazing work there. And I am _late_ to the game.  Can you please create a new branch of STP where you push your patch to STP?

**Comment by rgov** [comment]
[Here's a demo](https://ryan.govost.es/stp-web/index.html) of it working on a very simple query.

**Comment by msoos** [comment]
WOW. We must put this on the STP page! This is incredible work!!!

**Comment by msoos** [comment]
Correction *you*. Also, please put yourself as the creator, this is some amazing stuff!

**Comment by rgov** [comment]
I've remade the [STP website](https://stp.github.io/) with a live version there. There are obviously features missing like being able to see the counterexamples, and I want to make it build new versions automatically. (Though maybe only when we tag, since the WebAssembly file is pretty big.)

The old site has been moved over to [Read the Docs](https://stp.readthedocs.io/) but the inter-document links aren't configured yet so some of the content is lost.

I should see if we can get the old Google site taken down.

**Comment by msoos** [comment]
Thanks! Something is a bit odd, though:

https://stp.github.io/
https://stp.readthedocs.io/en/latest/

are both online? I think the Google site is down. But the above two are confusing even to me! :) Why do we host the docs on a different domain than the other stuff? Is there some reason for it?

**Comment by rgov** [comment]
We could host the docs ourselves, but Read the Docs has taken over the business of doc hosting for open source projects—they do continuous integration re-generation of the docs, make it searchable, let people browse documentation for different releases, etc.

The docs live inside the main source repo, and you can just modify the files in `docs/`. Hopefully this is what people are doing when they make major changes, to keep the documentation up to date.

If you want to change just the webpage, that's in the stp/stp.github.io repo.

**Comment by msoos** [comment]
OK, that sounds reasonable. I'll check out readthedocs.io, maybe I'll use it with CMS too :) Thanks again! I guess I'll close this now :)
