### ISSUE TITLE
Division by zero bug

### ISSUE THREAD

**Issue by ccadar** [stp/stp#206]
Using KLEE, we found a crash bug in STP related to the way it handles division by zero.  The bug is reported at https://github.com/klee/klee/issues/308, but I repeat it below.  

The problematic query, in SMT2 format, is the following:
```
; Query 6 -- Type: Validity, Instructions: 83
(set-logic QF_AUFBV )
(declare-fun unnamed () (Array (_ BitVec 32) (_ BitVec 8) ) )
(assert (let ( (?B1 (concat  (select  unnamed (_ bv1 32) ) (select  unnamed (_ bv0 32) ) ) ) ) (let ( (?B2 (concat  (select  unnamed (_ bv3 32) ) (concat  (select  unnamed (_ bv2 32) ) ?B1 ) ) ) ) (and  (and  (=  false (=  (_ bv0 32) ?B2 ) ) (=  false (=  (_ bv0 16) ?B1 ) ) ) (=  (_ bv0 32) (bvsrem  (_ bv16864560 32) ?B2 ) ) ) ) ) )
(check-sat)
(exit)
;   FAIL -- Elapsed: 1.298230e-01
;   Failure reason: SOLVER PROCESS INTERRUPTED
```

This doesn't crash STP from the command line, but when the query is constructed in KLEE, the following error trace is produced:
```
Fatal Error: BVConstEvaluator:division by zero error
error: STP Error: BVConstEvaluator:division by zero error
0  libLLVM-3.4.so.1 0x00002b0bc545f042 llvm::sys::PrintStackTrace(_IO_FILE*) + 34
1  libLLVM-3.4.so.1 0x00002b0bc545ee34
2  libpthread.so.0  0x00002b0bc5f25340
3  libc.so.6        0x00002b0bc6bb9cc9 gsignal + 57
4  libc.so.6        0x00002b0bc6bbd0d8 abort + 328
5  klee             0x00000000004efda9
6  klee             0x0000000000549397 stp::FatalError(char const*) + 55
7  klee             0x00000000005a7657
8  klee             0x00000000005a8f80 stp::NonMemberBVConstEvaluator(stp::STPMgr*, stp::Kind, std::vector<stp::ASTNode, std::allocator<stp::ASTNode> > const&, unsigned int) + 6336
9  klee             0x00000000005a9370 stp::NonMemberBVConstEvaluator(stp::ASTNode const&) + 96
10 klee             0x0000000000553332 SimplifyingNodeFactory::CreateTerm(stp::Kind, unsigned int, std::vector<stp::ASTNode, std::allocator<stp::ASTNode> > const&) + 194
11 klee             0x000000000054e5b7 NodeFactory::CreateArrayTerm(stp::Kind, unsigned int, unsigned int, std::vector<stp::ASTNode, std::allocator<stp::ASTNode> > const&) + 23
12 klee             0x00000000005cc64a stp::SubstitutionMap::replace(stp::ASTNode const&, std::unordered_map<stp::ASTNode, stp::ASTNode, stp::ASTNode::ASTNodeHasher, stp::ASTNode::ASTNodeEqual, std::allocator<std::pair<stp::ASTNode const, stp::ASTNode> > >&, std::unordered_map<stp::ASTNode, stp::ASTNode, stp::ASTNode::ASTNodeHasher, stp::ASTNode::ASTNodeEqual, std::allocator<std::pair<stp::ASTNode const, stp::ASTNode> > >&, NodeFactory*, bool, bool) + 1466
13 klee             0x00000000005cc1ef stp::SubstitutionMap::replace(stp::ASTNode const&, std::unordered_map<stp::ASTNode, stp::ASTNode, stp::ASTNode::ASTNodeHasher, stp::ASTNode::ASTNodeEqual, std::allocator<std::pair<stp::ASTNode const, stp::ASTNode> > >&, std::unordered_map<stp::ASTNode, stp::ASTNode, stp::ASTNode::ASTNodeHasher, stp::ASTNode::ASTNodeEqual, std::allocator<std::pair<stp::ASTNode const, stp::ASTNode> > >&, NodeFactory*, bool, bool) + 351
14 klee             0x00000000005cc3a6 stp::SubstitutionMap::replace(stp::ASTNode const&, std::unordered_map<stp::ASTNode, stp::ASTNode, stp::ASTNode::ASTNodeHasher, stp::ASTNode::ASTNodeEqual, std::allocator<std::pair<stp::ASTNode const, stp::ASTNode> > >&, std::unordered_map<stp::ASTNode, stp::ASTNode, stp::ASTNode::ASTNodeHasher, stp::ASTNode::ASTNodeEqual, std::allocator<std::pair<stp::ASTNode const, stp::ASTNode> > >&, NodeFactory*, bool, bool) + 790
15 klee             0x00000000005cc3a6 stp::SubstitutionMap::replace(stp::ASTNode const&, std::unordered_map<stp::ASTNode, stp::ASTNode, stp::ASTNode::ASTNodeHasher, stp::ASTNode::ASTNodeEqual, std::allocator<std::pair<stp::ASTNode const, stp::ASTNode> > >&, std::unordered_map<stp::ASTNode, stp::ASTNode, stp::ASTNode::ASTNodeHasher, stp::ASTNode::ASTNodeEqual, std::allocator<std::pair<stp::ASTNode const, stp::ASTNode> > >&, NodeFactory*, bool, bool) + 790
16 klee             0x00000000005ccb4e stp::SubstitutionMap::replace(stp::ASTNode const&, std::unordered_map<stp::ASTNode, stp::ASTNode, stp::ASTNode::ASTNodeHasher, stp::ASTNode::ASTNodeEqual, std::allocator<std::pair<stp::ASTNode const, stp::ASTNode> > >&, std::unordered_map<stp::ASTNode, stp::ASTNode, stp::ASTNode::ASTNodeHasher, stp::ASTNode::ASTNodeEqual, std::allocator<std::pair<stp::ASTNode const, stp::ASTNode> > >&, NodeFactory*) + 30
17 klee             0x0000000000566961 stp::EstablishIntervals::topLevel_unsignedIntervals(stp::ASTNode const&) + 2769
18 klee             0x000000000055a856 stp::STP::sizeReducing(stp::ASTNode, stp::BVSolver*, stp::PropagateEqualities*) + 2518
19 klee             0x000000000055bcaf stp::STP::TopLevelSTPAux(stp::SATSolver&, stp::ASTNode const&) + 1279
20 klee             0x000000000055ef7a stp::STP::TopLevelSTP(stp::ASTNode const&, stp::ASTNode const&) + 202
21 klee             0x0000000000526b49 vc_query_with_timeout + 185
22 klee             0x00000000004f4181 STPSolverImpl::computeInitialValues(klee::Query const&, std::vector<klee::Array const*, std::allocator<klee::Array const*> > const&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, bool&) + 2529
...
```
Any hints on what might cause this and how to debug this further?

**Comment by msoos** [comment]
Thanks, I'm looking into it!

By the way, a minor thing:
```
( (?B1 (concat  (select  unnamed (_ bv1 32) ) (select  unnamed (_ bv0 32) ) ) ) )
``
Could have a pair of brackets removed. I know, not important, but makes the reading easier :)

**Comment by msoos** [comment]
Note to self. Query is:
```
; Query 6 -- Type: Validity, Instructions: 83
(set-logic QF_AUFBV )
(declare-fun unnamed () (Array (_ BitVec 32) (_ BitVec 8) ) )
(assert
	(let
		( (?B1
			(concat  (select  unnamed (_ bv1 32) ) (select  unnamed (_ bv0 32) ) ))
		)
		(let
			( (?B2 (concat  (select  unnamed (_ bv3 32) ) (concat  (select  unnamed (_ bv2 32) ) ?B1 ) ) ) )
			(and  (and  (=  false (=  (_ bv0 32) ?B2 ) ) (=  false (=  (_ bv0 16) ?B1 ) ) ) (=  (_ bv0 32) (bvsrem  (_ bv16864560 32) ?B2 ) ) )
		)
	)
)
(check-sat)
(exit)
;   FAIL -- Elapsed: 1.298230e-01
;   Failure reason: SOLVER PROCESS INTERRUPTED
``

**Comment by msoos** [comment]
@ccadar The hard question is: what would you like the system to do with divison by zero? What should that be equal to? The problem here is that the constant propagator propagated a 0 around and it got to a divison-by-zero point. So the expression has a divison-by-zero no matter what the symbolic values are. It's non-trivial what to do there, there are a number of options. The SMT community has been dealing with this issue for a while year and here is the _very_ long discussion thread that came of it last year. I suggest reading Armin's comments who is quite the expert:

http://sourceforge.net/p/smtcomp/mailman/smtcomp-discussion/thread/539B35D0.10201%40csl.sri.com/#msg32458136

What do you think?

**Comment by ccadar** [comment]
In principle, KLEE should never send a division by zero to STP, as it checks all divisors for equality with zero.  I need to take a closer look at the query, which divisor is zero? 
Also, how that STP on the command line does not complain?

**Comment by TrevorHansen** [comment]
As per #223, it crashed via the API, but not via SMTLIB2 format because division-by-zero was previously handled differently in each. It won't crash now, but might not do what you expect..

**Comment by msoos** [comment]
@ccadar sometimes, KLEE cannot check on the divisons, because it takes complicated reasoning to find out that the division is a division by zero. This is what happened above. As per @TrevorHansen 's comment, things will be the same, and it won't "crash" (assert fail), but it will return -1 on such operations (all zero bits), which may not be how e.g. C interprets it (e.g. C might send a signal for division by zero and crash the program). So it's a tricky thing. For this to be handled in a way that is satisfactory, you probably want to have  QF_UFBV logic, which allows you to essentially define what to do. However,  QF_UFBV is a lot more expensive. QF_UFBV is "Unquantified formulas over bitvectors with uninterpreted function and predicate symbols". It's worth looking it up in SMT-LIBv2.5. For discussion over this issue, see: 

https://sourceforge.net/p/smtcomp/mailman/smtcomp-discussion/thread/CAExLfKdHA2xZgg5JUxTA0c4%2BNVtZ%3DzMKBvgf5thDNQiB1Kp7Vw%40mail.gmail.com/#msg32453062

It's a *long* thread but interesting, with everyone major explaining their points of view.

**Comment by TrevorHansen** [comment]
Clarifying, as per #223, unsigned division by zero will evaluate to 1 for now (irrespective of input language). Later, when the SMTLIB semantics are changed, we'll alter it to match them.

**Comment by ccadar** [comment]
Hi @msoos , @TrevorHansen , thanks for the update.  I don't think the problem is that KLEE cannot check divisions -- every time it constructs a division operation, it does just that.  From what I can see from #211 , where one simply adds the constraints x != 0 and uses x in a division/modulo operation, STP can try the value of 0 and run into a division by 0 (although the overall constraints do not allow this).  In such cases, can STP return incorrect results?  I'm not sure what you guys mean by "might not do what you expect" in such a case (where division by zero is NOT possible, but only happens during STP's solving process).  Thanks!

**Comment by msoos** [comment]
Hmmm... this needs further investigation. I will have more time from now on to work on STP, so hopefully I'll be able to figure out what is going on. Thanks for the report and that clue about x != 0.

**Comment by msoos** [comment]
@ccadar to me it seems that the semantics have now been fixed you won't get the issue as per above. I suggest you to re-open this issue in case we can find an issue where STP is crashing when used from the C interface. We can then debug and fix it using the (much easier) SMT2 interface, since the two are now equivalent. I hope everything is fixed now, as per Trevor's comment. If you properly guard all your calls, there should be no trouble :)
