### ISSUE TITLE
use cryptominisat instead of minisat?

### ISSUE THREAD

**Issue by iceman1001** [stp/stp#207]
I have a newbie question, can I use cryptominisat instead of minisat with STP?  Is there a make input to change or?  If its possible?

**Comment by iceman1001** [comment]
According to this,  ref ( https://github.com/stp/stp/blob/master/INSTALL.md )
it should autodetect it,  but that doesn't happens on my ubuntu14 system...

**Comment by iceman1001** [comment]
It finds it, but still wants minisat.

http://pastebin.com/0HZE5X5P

**Comment by msoos** [comment]
It still needs MiniSat, MiniSat is not optional, only CryptoMiniSat it. Note that you will need to pass the correct option (`--cryptominisat4`) to use CryptoMiniSat otherwise it defaults to MiniSat. Sorry for the inconvenience. You should be able to simple install MiniSat though:

```
sudo apt-get install minisat
```

Good luck!

Mate

**Comment by msoos** [comment]
Please close this issue if the above fixes your problem. Thanks!

**Comment by iceman1001** [comment]
yes, got it.  Thanks.
