### ISSUE TITLE
Crashing at smtcomp2016

### ISSUE THREAD

**Issue by TrevorHansen** [stp/stp#220]
STP with mult-threaded CMS has crashed on 28 benchmarks in one division.

https://www.starexec.org/starexec/secure/details/pairsInSpace.jsp?type=unknown&sid=560017&configid=158183&stagenum=1

The binary is here:
https://www.starexec.org/starexec/secure/details/solver.jsp?id=8120

Taking ndist.b.21497:
https://www.starexec.org/starexec/secure/details/benchmark.jsp?id=2977707

1) It runs properly on my machine.
2) In Valgrind's memcheck I get an error, but I also get the same error on about 40% of semi-random instances created by a fuzzer. So it doesn't seem particular to the ndist.b.. problem.
3) When I compile with santizer=ON, I get some errors, but they're all in the constantbv library and the STL, so it seems ok.
4) When I run with Valgrind's helgrind, I get lots of warnings, but I get lots of warnings when I run it on semi-random instances, too. So it doesn't seem particular to the ndist.b.. problem.
5) It seems to be seg-faulting in CMS SAT solving.
6) Single-threaded CMS seems to be running ok.
7) Running it eight times on star-exec, it fails each time. So at least it is reproduce-able..

I think a reasonable next step is to compile CMS4 statically, and output a CNF from STP, then solve using CMS4.

**Comment by msoos** [comment]
Crap, I have an idea. This is crazy, but I hate it. I use this:

```
static inline double cpuTime(void)
{
    struct rusage ru;
    #ifdef RUSAGE_THREAD
    int ret = getrusage(RUSAGE_THREAD, &ru);
    #else
    int ret = getrusage(RUSAGE_SELF, &ru);
    #endif

    assert(ret == 0);

    return (double)ru.ru_utime.tv_sec + (double)ru.ru_utime.tv_usec / 1000000.0;
}
```

Now the issue is that RUSAGE_THREAD is not available before kernel 2.6.26, which came out in 2009. Which may be running on StarExec. The old Scientific Linux in particular doesn't have it (2.4 kernel). It's _painful_.

Here is one compiled without RUSAGE_THREAD: 

http://www.msoos.org/private/stp-2.1.2.gz

Can you please test it on StarExec? Or can you please tell me how to do it? I really tried, and I still can't do it. A short how-to would really help. I know, this is embarrassing, but I still have trouble with StarExec.

**Comment by msoos** [comment]
I booted the OVA from starexec (took the stable, not the beta one), ran it like:

```
./stp-2.1.2 --cryptominisat4 --threads 4 ndist.a.21996.smt2
```

and it's still running. I am lost. The VM has 2GB of RAM and hasn't ran out of it (at ~32% mem use now, according to `top`). I have no idea what is going on and frankly, I'm a bit frustrated about this. I'd like to ask the organisers to give us at least some clue of what's going on. I cannot reproduce it, and I think by this point we both tried. Do you think that's a good idea?

Mate

**Comment by TrevorHansen** [comment]
This occurs when processing from a file CNF, so it's not STP related.
