### ISSUE TITLE
Finding LIT when doing a travis CI trusty build

### ISSUE THREAD

**Issue by TrevorHansen** [stp/stp#251]
I've tried to upgrade TravisCI to Ubuntu 14, it seems to work OK, except it can't find LIT. 

I get this error message:
pkg_resources.DistributionNotFound: The 'lit==0.5.0' distribution was not found and is required by the application

pip install lit, seems to work ok.

Does anyone have any ideas about what's gone wrong?

Thanks.

**Comment by msoos** [comment]
This is incredibly painful and I have no idea what's going on. I'm also investigating and have poured in at least 2h of work. It's the same issue in builds of CMS -- I'm trying to switch over to Trusty too. So, same issue there, no idea :S If you have any idea, please let me know. Here is what I tried:

* `sudo -H pip install lit`
* running `sudo -H pip install --upgrade pip` before
* downloading lit-0.5.0.tar.gz and building&installing it that way

No luck :S

**Comment by msoos** [comment]
OK, this is fixed now, huh. Closing. The issue was that "lit" should be called on its own:

`lit --version`

but we called it as:

`python lit --version`

and that failed.

**Comment by delcypher** [comment]
@TrevorHansen Can you please point me at the failing build?

@msoos @TrevorHansen You need to be incredibly careful how you use `pip` in TravisCI. In TravisCI the environment is setup to use `virtualenv` by default which means you **should run the pip tool without sudo**. If you run `sudo pip` you are using the system (i.e. Ubuntu's) `pip` rather than the virtualenv `pip` which means whatever you install with `sudo pip` will not be visible in the `virtualenv` environment.

**Comment by msoos** [comment]
Ahh. Well, I'll take a peek again. As I said, the "lit" tool just works now, without specifying the python version by running it under python, so I'm kinda happy now. It works for both CryptoMiniSat and STP. Do you think we should run it under python2.7 explicity and fix the install by doing "pip install lit" instead of "sudo -H pip install lit"? I'm happy to try of course, it just has been a very painful experience trying to fix this, so I'm reluctant to break something that is fixed now :)

**Comment by msoos** [comment]
Thanks for the pro tip about the pip virtualenv in Travis. This was not clear to me at all :S I'm a noob.

**Comment by delcypher** [comment]
@msoos 
> Ahh. Well, I'll take a peek again. As I said, the "lit" tool just works now, without specifying the python version by running it under python, so I'm kinda happy now.

The only reason I prefixed the lit tool with the python executable was because I was concerned it wouldn't work on Windows without it. I never really tested this so you change is probably fine for now.

> It works for both CryptoMiniSat and STP. Do you think we should run it under python2.7 explicity and fix the install by doing "pip install lit" instead of "sudo -H pip install lit"? I'm happy to try of course, it just has been a very painful experience trying to fix this, so I'm reluctant to break something that is fixed now :)

In TravisCI you should replace any `sudo pip ...` invocations with `pip ...` to avoid massive headaches in the future. I was bitten really hard by this confusing behaviour a while back :(

Note here's the TravisCI docs on this:

https://docs.travis-ci.com/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs

They probably ought to mention the pitfall of using `sudo`...

**Comment by msoos** [comment]
Wow, thanks for the link! I'll keep an eye out. We are fixing the Windows build now with Felix (yay!) and he is working on making the "lit" thing work for tests, it seems OK for now, but I'll keep an eye out for the pitfall of possibly having to run it under python. Thanks again!
