### ISSUE TITLE
CNF not generated 

### ISSUE THREAD

**Issue by awanish-pandey** [stp/stp#260]
I want to generate cnf file for sm2 file. smt2 file contains
(set-logic QF_AUFBV )
(declare-fun a () (Array (_ BitVec 32) (_ BitVec 8) ) )
(assert (=  (_ bv0 32) (concat  (select  a (_ bv3 32) ) (concat  (select  a (_ bv2 32) ) (concat  (select  a (_ bv1 32) ) (select  a (_ bv0 32) ) ) ) ) ) )
(check-sat)
(exit)
when I am doing `stp --output-CNF a.smt2` it is not generating any cnf file.

**Comment by msoos** [comment]
Yes, this has been an issue and frankly, I don't think we'll be able to deal with this. The issue is that STP does a lot of simplifications. If these simplifications lead to an obvious UNSAT or SAT, it will output this solution and exit, without ever passing the problem to the SAT solver. Hence, no CNF is generated. I am now updating the option to indicate this behaviour.

**Comment by msoos** [comment]
I hope the above explains it well. There is no plan to "fix" this as this is more like a feature than anything else -- there is no need to generate the CNF, and so we skip generating it :)
