### ISSUE TITLE
undefined refernce error while installing STP

### ISSUE THREAD

**Issue by Anum-Tahir** [stp/stp#345]
Hello. I am trying to build and install STP latest version on Ubuntu 19.1. I ran these commands:
$ sudo apt-get install cmake bison flex libboost-all-dev python perl zlib1g-dev minisat
$ git clone https://github.com/stp/stp.git
$ cd stp
$ git checkout tags/2.3.3
$ mkdir build
$ cd build
$ cmake ..
$ make
$ sudo make install

it worked successfully till cmake but when i run make command, the following error pops up
 
![91593161_645813816153502_2865050315248369664_n](https://user-images.githubusercontent.com/19519710/77915551-1e383780-72b1-11ea-9296-3bee480b0863.jpg)

Before running the above mentioned commands, i have first installed ministat using the following commands:
$ git clone https://github.com/stp/minisat.git
$ cd minisat
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ ../
$ sudo make install

Ministat is successfully installed and is now in the list of my installed stuff on ubuntu. 

Please guide on what the error is about and how to resolve it. Thank you!

**Comment by rgov** [comment]
Hi @Anum-Tahir could you please include the output of the commands inside a [code block](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) so we can see it all?

In particular I'd like to see the output of the `cmake` command. Because you are installing Minisat in /usr/local, perhaps when you configured STP, it could not find it there.

**Comment by Anum-Tahir** [comment]
Thank you very much for reaching out @rgov. I read your email regarding it being a 4 year old issue. I am sorry for being too late on the reply. The reason for it is that I am now unable to log into my ubuntu. It is just extremely slow and doesn't boot at all. First, i thought it was some memory issue (I have installed ubuntu using virtual box within windows). but since it got installed and worked totally fine earlier, this is probably not related to the memory. This problem is not related to the thread i started but it will be much appreciated if you can guide me on this. I have already tried uninstalling and reinstalling the machine, it worked and got completely installed but didn't boot again after the restart. 

I will look into the README in the project for the latest build instructions as you directed once I can log in and start using ubuntu again. I will try that out while building STP and give you feedback weather i get another (new type of) error. Thank you very much for your help!

**Comment by rgov** [comment]
Hi @Anum-Tahir, unfortunately I cannot help with your Ubuntu. If you are able to get it to work again, you can create a snapshot in Virtual Box so that if a problem happens again, you can rewind back to the snapshot. You could also try using Docker. Finally, STP is supported on Windows. But I do not use Windows or Ubuntu.

You can also try: https://www.askubuntu.com

**Comment by Anum-Tahir** [comment]
Alright. I hope that works. Once again thanks a lot for your help !
