### ISSUE TITLE
SMT-COMP 2021

### ISSUE THREAD

**Issue by TrevorHansen** [stp/stp#399]
There's new a cloud division at SMT-COMP 2021 that runs on 100 machines.

Overview:  https://smt-comp.github.io/2021/news/2021-02-05-parallel-and-cloud-tracks
Sample submission: https://github.com/aws-samples/aws-batch-comp-infrastructure-sample

The easiest seems to be to create a CNF from STP, then send it to a distributed SAT solver. 

@msoos is it easy to use CMS for distributed solving?

**Comment by msoos** [comment]
Hi,

Sorry for the late reply. There is an MPI version of CryptoMiniSat -- I
haven't used it in a while, but it's not supposed to be too difficult to
make work. I'll play with it and get back to you :)

Cheers,

Mate

**Comment by conp-solutions** [comment]
By now, I extended the MergeSat solver to be capable of being used as backend of the HordeSat for MPI (and the issues from last year have been addressed). Similarly to a distributed CryptoMiniSat, a distributed STP would have to translate the input problem to CNF first, before using a distributed SAT solver. Either, STP is integrated into the distributed SAT solver and each node translates the formula, or the translated CNF would have to be stored back to S3 so that each compute node could download it from there for further solving. Not sure whether distributing these CNFs via MPI broadcast would be faster.

I wonder we should submit the portfolio solve of last year to this years parallel track. Last years best parallel SAT solver only used 32 out of the 64 available cores - given virtualization and resource sharing, that makes sense. @msoos, is it sensible to combine a 28core parallel CryptoMinisat with 2 MergeSat (SAT and UNSAT configuration), 1 Riss and 1 MiniSat ?

**Comment by andrewvaughanj** [comment]
> 1 MiniSat 

Do we have instances where the MiniSat configuration beats any of these other configurations?

For the cost of one thread, it feels it is probably fine to "waste" it, but I am just curious if we have any examples where vanilla MiniSat beats the other configurations.

**Comment by msoos** [comment]
Hi All,

First of all, thanks for the great points!

Regarding the parallel system: sure, a multi-threaded MergeSat  + a multi-threaded CMS + a single-threaded MiniSat sounds like a good parallel setup! Re @andrewvaughanj : hmmm... not sure about MiniSat adding too much, actually, good point. @conp-solutions what do you think?

Regarding the MPI system. For these cases, in my opinion, the issue is not really about distributing the CNF -- you may gain 10-15 seconds one way or another, but given the timelines, that's rather small? I think CMS-MPI uses the broadcast thing. The simplest setup would be to have the main node run STP as a binary, output the problem to CNF, and then launch  Hordesat+MergeSat/CMS+MPI solver. Of course it would be fun to have STP in an MPI way, but that's kinda hard... unless someone wants to pick that up. But that sounds like at least a month of work to me, so maybe not worth it? I don't really know :(

What do you all think?

**Comment by andrewvaughanj** [comment]
> The simplest setup would be to have the main node run STP as a binary, output the problem to CNF, and then launch Hordesat+MergeSat/CMS+MPI solver.

Agreed.

I guess we're just doing QF_BV, right? So everything can be done eagerly.

Why am I asking? Well, I started thinking about creating SMT-based models from the SAT-based assignment (and I started getting ahead of myself :joy:), but I guess this is just talking about SAT/UNSAT, so if we're doing eager bit-blasting then the result from the distributed SAT solver can just be passed back.

If this is the case, then I guess we can do it with a shell-script, right? Run STP -> dump CNF -> run CNF -> return whatever SAT solver comes back first.

**Comment by andrewvaughanj** [comment]
(no "A" -> no theory solving -> totally eager instances)

**Comment by TrevorHansen** [comment]
> If this is the case, then I guess we can do it with a shell-script, right? Run STP -> dump CNF -> run CNF -> return whatever SAT solver comes back first.

Yes, I agree that doing it via a shell script is easiest.

The other thing I want to do is: run each QF_BV SMTLIB problem in the benchmark scrambler several times with different seeds, then send them to STP with --exit-after-CNF, then profile the slow ones, and then speedup those processing steps in STP. 

From memory there are problems in SMTLIB for which STP won't get to SAT solving within the time limit. Some processing steps are super slow (and it's probably best to cut them short).

**Comment by TrevorHansen** [comment]
I've submitted our entry into the main part of SMT-COMP just now. We've got until the 13-June to amend the entry. There's a few basic improvements that I'd like to make. If there's anything in particular that you'd like done, let me know and maybe we can work on it together.

I haven't submitted the parallel or distributed entries. They're submitted differently - via a docker instance on github. We need a placeholder entry submitted this month. Then (like the main part) we have until the 13th June to submit a final one.

Some questions:
* Is it easy for someone to package up STP with docker for submission to the parallel division?  I've not done it before.
* Do we try for the distributed division? @msoos  can the MPI CMS be ready for the 13th?

**Comment by conp-solutions** [comment]
I had a quick look yesterday. I can likely modify the existing docker file to work for the parallel track, based on the submission of MergeSat to last years parallel SAT track.This Dockerfile would be used in the competition only, i.e. it will stay in a separate branch.Furthermore, i would use the portfolio parallel script we submitted 2 years ago, let stp generate a cnf, and then run solvers in parallel.Any objections to the above outline?Best,Norbert

**Comment by conp-solutions** [comment]
@TrevorHansen Can you please submit a dummy for the parallel division? The repository+branch of my above PR can likely be used for that. In case it does not work with the competition S3 scenario, I can iterate accordingly.

**Comment by msoos** [comment]
Actually, I have created an MPI version of CMS as well :) Shall we compete in that track, too? And of course we should submit for the parallel -- the MPI is just parallel + MPI between the nodes with a master node. Not extremely efficient, but may work :)

**Comment by msoos** [comment]
OK, I am an idiot, I see that I have to send an email to aws-smt-comp-2021@googlegroups.com to compete there. So I'll do that now and then set it up until June 13th. I'll have STP run on a single thread, single machine to blast, then CMS do the MPI magic with their AWS+Docker+SSH+MPI setup from https://github.com/aws-samples/aws-batch-comp-infrastructure-sample following https://github.com/aws-samples/aws-batch-hordesat-sample .

**Comment by conp-solutions** [comment]
Do you also register for the parallel track in that email, and cc the others here?

**Comment by msoos** [comment]
I am registering to the Cloud track only, right? The other registrations are done by you/Trevors, I think, right?

I am CC'ing everyone for the Cloud track, yep! Code will be at:

https://github.com/stp/smtcomp-cloud-2021/

If that's OK with you?

**Comment by TrevorHansen** [comment]
We submit a Docker entry into two divisions -  the cloud and the parallel. I've not submitted to either.

The cloud division is 100 machines (so distributed), the parallel division is a single machine with 64 virtual cores.

From what I've seen so far, we've emailed to enter the cloud, but not the parallel. @msoos, today I think it's just a single line email to the organisers asking to enter that parallel division. I'll do it if you don't?

**Comment by msoos** [comment]
Yep, if you could do it, that'd be nice! I'll take care of the Cloud division, I promise :) I'll also send some regular updates here about the Cloud setup, so everyone can follow. If you feel like helping, I can also give you access to the AWS account. Just beware that there will likely be limited credit, and AWS doesn't offer a cutoff feature, so cost can accumulate past the credit. Drop me a mail if you feel like playing with it, I'll create an IAM user for you.

**Comment by msoos** [comment]
Ahhhh, now I see! Sorry for sending the mail only for the cloud. I thought you'd send it for the parallel in a different mail, with different name, etc. But I see I could have done it in one go, better. Sorry :disappointed:

**Comment by TrevorHansen** [comment]
Thanks everyone for getting this sorted. Just a question, is it going to be possible to have a single Docker image submitted for both the cloud and parallel competitions? Or do we need to work towards two separate entries?

**Comment by conp-solutions** [comment]
I tried that. IIUC, the difference between the two would be the presence of certain environment variables that indicate that your container is running via AWS batch. Ultimately, that detection is not official, so I would not rely on it. Hence, while being less maintainable, having 2 builds might be the better option.If you want me to push my branch somewhere more available, i can happily do that.

**Comment by andrewvaughanj** [comment]
Quick query: does anyone know the logics that are being used in these tracks? I assume that we're entering STP *just* for QF_BV, right?

I don't think we enter regular (== non-cloud, non-parallel) QF_ABV because we don't have extensionality, and even if we *did*, I'm not sure how we can do these parallel/distributed instances with the refinement loop.

Also, do any of the cloud/parallel tracks need models or is it just SAT/UNSAT?

**Comment by conp-solutions** [comment]
I do not know these details. We could just add that question to the email thread, and ask the organizers to add the answer to the web pages as well.

**Comment by TrevorHansen** [comment]
Yes @andrewvaughanj , we're entering STP just into QF_BV. I think the cloud and parallel divisions are just single problems  expecting either SAT/UNSAT back as the answer.

**Comment by conp-solutions** [comment]
https://smt-comp.github.io/2021/participants.html lists the participating solvers.

Should I place my modifications into a separate repository under the STP namespace, or should we make this a branch of the main repository for now? I can use my AWS account for testing the setup in the AWS parallel track environment. It worked well when using a single SAT solver, and it already runs locally.

**Comment by conp-solutions** [comment]
I pushed a rebased update, an will announce that in the email list now, announcing that we might change the git commit ID and repo eventually, moving the code from testing into a stable branch/repo.

#404

**Comment by msoos** [comment]
Thanks! Please let me know when you are good -- I am putting together the cloud setup, and will need a final STP. I plan to use:

```
./stp --SMTLIB2 --output-CNF --exit-after-CNF
[check if sat/unsat is printed. If not, then:]
mpirun -c N ./cryptominisat5_mpi output_0.cnf
[check if UNSAT -> print "unsat", if SATISFIABLE, print "sat"]
```

So that's pretty easy :) CryptoMiniSat MPI system seems to be working, and the AWS setup also seems to be working, including building CMS, STP + running on a CNF in MPI mode.

I will need to implement and debug the `SMT-to-CNF` (the main node runs STP, not a big deal) and `CNF-solution-to-SMT-solution` (bash checks for output) parts, but they should be relatively simple. The code is currently at https://github.com/stp/smtcomp-cloud-2021. 

Please let me know when STP is ready, I will then update. Note that I don't need to have latest CMS/Riss/MinSat/etc in my version of STP. I only need the SMT->CNF to be correct and complete. So if that part is ready as-is, then I'm good :)

**Comment by msoos** [comment]
Update: I believe I am now good to go with https://github.com/stp/smtcomp-cloud-2021. You can check it out, if you like. I plan to  mail the organizers about the `main` branch commit `02e4a5e90e7e626da9092688565d6166a022346a` being good. I will do some more tests in the meanwhile.

Would you be so kind as to check it? It should work with the bog-standard [aws-batch-comp-infrastructure-sample](https://github.com/aws-samples/aws-batch-comp-infrastructure-sample). Let me know what you think!

Thanks and thanks in advance for all the work put into STP for the competition,

Mate

**Comment by TrevorHansen** [comment]
Thanks @msoos  and @conp-solutions for the big effort!

I've had a first go at the system description:
https://github.com/stp/docs/blob/master/smt2021-descr/descr.pdf

The organisers will take the system description from our repository. I've done it in a hurry, so I'm sorry if I've down-played anyone's recent contributions!  Please correct it.

I appreciate it's all very last minute, but I've pushed some changes in mostly to help the distributed & parallel editions. I've added some depth limits and a timeout so that more benchmarks get to CNF generation. Previously 67 benchmarks didn't finish CNF generation in 120 seconds, with the patch it's 35.  It will mean more time for sat solving. No worries if it's finalised already.

**Comment by msoos** [comment]
Thanks! I updated by adding info about the Cloud Track. @conp-solutions maybe you can add some text about the parallel version?

**Comment by conp-solutions** [comment]
I added some, and fixed your changes. As I do not have push permissions, I created a PR: https://github.com/stp/docs/pull/5

**Comment by msoos** [comment]
Wow, I am still living in 2020, I swear! Sorry, my internal clock stopped counting when Corona hit :S Thanks for fixing it up!

**Comment by msoos** [comment]
BTW, thanks Trevor for pushing, I am now using latest, i.e. 876589d45f656f13cefeb04a2f13005d0fa0c932 with my patch for MiniSat constants https://github.com/stp/stp/pull/406 for the Cloud track. We should merge that PR **after** the competition.

**Comment by TrevorHansen** [comment]
Part of the SMT-COMP is being run. So far only the single instance division has finished with STP a close third. It's a great effort! Thanks everyone.

https://www.starexec.org/starexec/secure/explore/spaces.jsp?id=443642
