### ISSUE TITLE
how to get old language reference web page？

### ISSUE THREAD

**Issue by xuanyi-ge** [stp/stp#445]
key words like BVPLUS() BVXOR() ASSERT()

**Comment by aytey** [comment]
Are you talking about the API or are you (actually) looking for the CVC input language?

If you want the latter:

- https://github.com/stp/stp/blob/2.3.3/docs/cvc-input-language.rst

However, this document was deleted from master because the CVC language is pretty much dead to the STP team; we will be totally unable to support you on questions related to that input format.
