### ISSUE TITLE
Decide what to do with generated query tests

### ISSUE THREAD

**Issue by delcypher** [stp/stp#79]
The new testing infrastructure has an option (`TEST_GENERATED_QUERIES`) to enable these queries but currently this will make the build system fail because I wasn't sure what to do here.

We should decide if we want these tests and if so how we want to implement executing them.

**Comment by msoos** [comment]
I have deleted a bunch of them. There is a much more comprehensive, more interesting set of tests in starexec, where you can download all the problems used for the competition. That's how I develop my SAT solver, too. I take the examples from previous competitions to test the speed against. These are not really 'tests' for bugs. For speed tests, we should be using updated tests from the past competitions, not keeping around stale examples from many years ago.

Please delete anything that is not actually runnable (too long to run) during a "make check" or that is too big to keep around (hundreds of KB gzipped, etc)

**Comment by msoos** [comment]
I have now added a LOT of ASSERT_TRUE/ASSERT_FALSE to the tests :) They now actually assert something. Also, they run ctest so they can be run on Windows -- and it turns out we have some issues, but that's a different beast and needs a different set of fixes. I think a lot of the tests have now been really cleaned up. Again, I think it's best to focus. We are a lot cleaner than we were before :)
